### ISSUE TITLE
License options: liberal and viral to choose for plugins

### ISSUE THREAD

**Issue by sjaehn** [sjaehn/lv2tutorial#13]

**Comment by mxmilkiib** [comment]
Copyleft and permissive

**Comment by BrunoVernay** [comment]
MIT license is fine. (What I see in enterprise is that GPL3 is an instant showstopper. As a result, it gets less chances of contribution.)

**Comment by redtide** [comment]
> Xputty uses the 0BSD license and some parts use the academic free license 2.0 and/or LGPL2.0+. This shouldn't be a problem.

if the licenses conditions are met there are no problems.

> But, in some of the upcoming videos I'll use the B.Widgets toolkit which is GPL3+. This should be fine for this repo with its source code files and the documentation. However, compiled binaries from this lv2tutorial repo can't be distributed under the MIT license.

I think important is the source code and documentation files can be used as reference for different projects using MIT. If they contains viral licensed code can be used as combined licenses.

**Comment by sjaehn** [comment]
Checked. MIT is fine for BMap.hpp. As this one isn't published somewhere else yet.
