### ISSUE TITLE
LV2 is available for any system, not just macOS + Windows + Linux

### ISSUE THREAD

**Issue by falkTX** [sjaehn/lv2tutorial#3]
You mention that LV2 is available for these 3 systems, in a way that sounds like it only works on these 3 systems.
But LV2, being a specification, works for any compatible system. There are no requirements whatsoever on the LV2 side, you dont even need to be using C or C++, people have successfully written D and Rust LV2 plugins already.

**Comment by sjaehn** [comment]
Yes, but this are the three best known systems. And believe me, there are many bedroom and also professional music producers out there with their Macs who don't know the existence of any other system. Maybe they know Windows, but nothing else. The same with many Windows users. Window, maybe Mac, but nothing else.

I know that LV2 is also available on a lot of other systems. And I know that the FreeBSD community is very engaged in this topic. Big thanks to them!

This tutorial will target beginners. I could flood them with a lot of information, like a never ending list on which systems LV2 is running. Or which alternative packages they may use. For each system, respectively. But then it would be video I wouldn't like to watch anymore. Therefore, I will simplify a lot of things.

The programming languages are another topic. And I will make a video about it later in this series. But first of all I busy to make a video explaining how LV2 plugins technically work inside a host. And then I will make a video about the signal flow and realtime before talking about programming languages. I'd be glad if I can ask YOU to check these videos before I make them public.
