### ISSUE TITLE
Maybe having a forum to discuss this tutorial ?

### ISSUE THREAD

**Issue by BrunoVernay** [sjaehn/lv2tutorial#4]
Like for example I would like to have autocompletion for lv2, rdf, doap ...
I installed "Stardog RDF Grammars" the grammar is highlighted, but there is no autocompletion.
I tried to use `lv2lint` without success (I did not investigate much)

**Comment by sjaehn** [comment]
1) Thanks for the README fix :-). 

2) I also don't use autocompletion for turtle. 

3) lv2lint can be used once the plugin is built and installed. The name might be misleading. BTW, lv2lint will complain about myAmp as I did some simplifications like the missing plugin version. 

4) The primary place for discussion about the videos should be under the video. But also feel free to ask here. I didn't think about a discord channel or sth. else, yet.

**Comment by redtide** [comment]
Enable the discussions feature?

**Comment by sjaehn** [comment]
Good idea, the discussion feature is now switched on: https://github.com/sjaehn/lv2tutorial/discussions/17
